### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by moore3071** [osurb/osurb.github.com#1]
Hey guys, I know it's been a while since you guys have looked at this repo, but I was wondering if it would be possible for you guys to throw a license on this repo if you can agree on one.

CWDG (what osurb formerly was) has forked this repo and used it as the base for their website. A lot of their content is currently licensed under MIT (which they'd love to see here for simplicity sake)

**Comment by jefflembeck** [comment]
Done!

**Comment by moore3071** [comment]
Thanks so much!
